# Previsão do Preço de Casas com Regressão Linear

Dataset: [House Sales in King County, USA](https://www.kaggle.com/harlfoxem/housesalesprediction)

In [48]:
import pandas as pd
base = pd.read_csv('data/house-prices.csv')

In [49]:
base.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view     ...      grade  sqft_above  \
0      5650     1.0           0     0     ...          7        1180   
1      7242     2.0           0     0     ...          7        2170   
2     10000     1.0           0     0     ...          6         770   
3      5000     1.0           0     0     ...          7        1050   
4      8080     1.0           0     0     ...          8        1680   

   sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
0              0      1955             0    98178  47.5112 -122.257   
1            400      1951          1991    98125  47.7210 -122.319   
2              0      1933             0    98028  47.7379 -122.233   
3            910      1965             0    98136  47.5208 -122.393   
4              0      1987             0    98074  47.6168 -122.045   

   sqft_living15  sqft_lot15  
0           1340        5650  
1           1690        7639  
2           2720        8062  
3           1360        5000  
4           1800        7503  

[5 rows x 21 columns]

In [50]:
base.count()

id               21613
date             21613
price            21613
bedrooms         21613
bathrooms        21613
sqft_living      21613
sqft_lot         21613
floors           21613
waterfront       21613
view             21613
condition        21613
grade            21613
sqft_above       21613
sqft_basement    21613
yr_built         21613
yr_renovated     21613
zipcode          21613
lat              21613
long             21613
sqft_living15    21613
sqft_lot15       21613
dtype: int64

In [51]:
X = base.iloc[:, 5:6].values
y = base.iloc[:, 2:3].values

In [52]:
X

array([[1180],
       [2570],
       [ 770],
       ...,
       [1020],
       [1600],
       [1020]])

In [53]:
y

array([[221900.],
       [538000.],
       [180000.],
       ...,
       [402101.],
       [400000.],
       [325000.]])

In [54]:
from sklearn.preprocessing import StandardScaler
scaler_x = StandardScaler()
X = scaler_x.fit_transform(X)
scaler_y = StandardScaler()
y = scaler_y.fit_transform(y)

/home/felipe/.local/share/virtualenvs/tensorflow-machine-learning-deep-learning--rkUGFC5q/lib/python3.6/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/home/felipe/.local/share/virtualenvs/tensorflow-machine-learning-deep-learning--rkUGFC5q/lib/python3.6/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [55]:
X

array([[-0.97983502],
       [ 0.53363434],
       [-1.42625404],
       ...,
       [-1.15404732],
       [-0.52252773],
       [-1.15404732]])

In [56]:
y

array([[-0.86671733],
       [-0.00568792],
       [-0.98084935],
       ...,
       [-0.37586519],
       [-0.38158814],
       [-0.58588173]])

In [57]:
import tensorflow as tf

In [58]:
colunas = [tf.feature_column.numeric_column('x', shape=[1])]
colunas

[_NumericColumn(key='x', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)]

In [59]:
regressor = tf.estimator.LinearRegressor(feature_columns=colunas)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/tmp/tmptmdf4tet', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7ffa218e1390>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


### Separando base de dados em treinamento e testes

In [60]:
from sklearn.model_selection import train_test_split
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X, y, test_size=0.3)

In [61]:
X_treinamento.shape

(15129, 1)

In [62]:
y_treinamento.shape

(15129, 1)

In [63]:
X_teste.shape

(6484, 1)

In [64]:
y_teste.shape

(6484, 1)

In [65]:
funcao_treinamento = tf.estimator.inputs.numpy_input_fn(
    {'x': X_treinamento}, y_treinamento, batch_size=32, num_epochs=None, shuffle=True
)

In [66]:
funcao_teste = tf.estimator.inputs.numpy_input_fn(
    {'x': X_teste}, y_teste, batch_size=32, num_epochs=1000, shuffle=False
)

In [67]:
regressor.train(input_fn=funcao_treinamento, steps=10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Saving checkpoints for 0 into /tmp/tmptmdf4tet/model.ckpt.
INFO:tensorflow:loss = 82.50751, step = 1
INFO:tensorflow:global_step/sec: 604.561
INFO:tensorflow:loss = 13.804888, step = 101 (0.166 sec)
INFO:tensorflow:global_step/sec: 642.591
INFO:tensorflow:loss = 10.523342, step = 201 (0.156 sec)
INFO:tensorflow:global_step/sec: 510.082
INFO:tensorflow:loss = 16.223581, step = 301 (0.196 sec)
INFO:tensorflow:global_step/sec: 735.897
INFO:tensorflow:loss = 12.123659, step = 401 (0.136 sec)
INFO:tensorflow:global_step/sec: 701.775
INFO:tensorflow:loss = 7.855687, step = 501 (0.142 sec)
INFO:tensorflow:global_step/sec: 639.227
INFO:tensorflow:loss = 9.498236, 

INFO:tensorflow:global_step/sec: 410.233
INFO:tensorflow:loss = 6.8921022, step = 7701 (0.243 sec)
INFO:tensorflow:global_step/sec: 423.338
INFO:tensorflow:loss = 23.149643, step = 7801 (0.237 sec)
INFO:tensorflow:global_step/sec: 517.108
INFO:tensorflow:loss = 7.7181773, step = 7901 (0.194 sec)
INFO:tensorflow:global_step/sec: 432.78
INFO:tensorflow:loss = 32.654583, step = 8001 (0.237 sec)
INFO:tensorflow:global_step/sec: 474.53
INFO:tensorflow:loss = 9.776735, step = 8101 (0.203 sec)
INFO:tensorflow:global_step/sec: 543.847
INFO:tensorflow:loss = 8.475598, step = 8201 (0.184 sec)
INFO:tensorflow:global_step/sec: 558.34
INFO:tensorflow:loss = 23.284298, step = 8301 (0.179 sec)
INFO:tensorflow:global_step/sec: 421.287
INFO:tensorflow:loss = 51.693577, step = 8401 (0.241 sec)
INFO:tensorflow:global_step/sec: 574.947
INFO:tensorflow:loss = 11.835712, step = 8501 (0.170 sec)
INFO:tensorflow:global_step/sec: 474.94
INFO:tensorflow:loss = 15.1340275, step = 8601 (0.215 sec)
INFO:tensorflow

In [68]:
metricas_treinamento = regressor.evaluate(input_fn=funcao_treinamento, steps=10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2019-01-08-01:57:45
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmptmdf4tet/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Evaluation [5000/10000]
INFO:tensorflow:Evaluation [6000/10000]
INFO:tensorflow:Evaluation [7000/10000]
INFO:tensorflow:Evaluation [8000/10000]
INFO:tensorflow:Evaluation [9000/10000]
INFO:tensorflow:Evaluation [10000/10000]
INFO:tensorflow:Finished evaluation at 2019-01-08-01:58:00
INFO:tensorflow:Saving dict for global step 10000: average_loss = 0.49414554, global_step = 10000, label/mean = -0.0040014153, loss = 15.812657, prediction/mean = -0.013690858
INFO:tensorflow:Saving 'checkpoint_p

In [69]:
metricas_teste = regressor.evaluate(input_fn=funcao_teste, steps=10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2019-01-08-01:58:29
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmptmdf4tet/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Evaluation [5000/10000]
INFO:tensorflow:Evaluation [6000/10000]
INFO:tensorflow:Evaluation [7000/10000]
INFO:tensorflow:Evaluation [8000/10000]
INFO:tensorflow:Evaluation [9000/10000]
INFO:tensorflow:Evaluation [10000/10000]
INFO:tensorflow:Finished evaluation at 2019-01-08-01:58:41
INFO:tensorflow:Saving dict for global step 10000: average_loss = 0.5389696, global_step = 10000, label/mean = 0.009826587, loss = 17.247026, prediction/mean = -0.01508721
INFO:tensorflow:Saving 'checkpoint_path'

In [70]:
metricas_treinamento

{'average_loss': 0.49414554,
 'label/mean': -0.0040014153,
 'loss': 15.812657,
 'prediction/mean': -0.013690858,
 'global_step': 10000}

In [71]:
metricas_teste

{'average_loss': 0.5389696,
 'label/mean': 0.009826587,
 'loss': 17.247026,
 'prediction/mean': -0.01508721,
 'global_step': 10000}

### Previsões

In [72]:
import numpy as np
novas_casas = np.array([[800], [900], [1000]])
novas_casas

array([[ 800],
       [ 900],
       [1000]])

In [73]:
novas_casas = scaler_x.transform(novas_casas)
novas_casas

/home/felipe/.local/share/virtualenvs/tensorflow-machine-learning-deep-learning--rkUGFC5q/lib/python3.6/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


array([[-1.39358923],
       [-1.28470655],
       [-1.17582386]])

In [74]:
funcao_previsao = tf.estimator.inputs.numpy_input_fn({'x': novas_casas}, shuffle=False)

In [75]:
previsoes = regressor.predict(input_fn=funcao_previsao)

In [76]:
previsoes

<generator object Estimator.predict at 0x7ffa20d9d728>

In [77]:
list(previsoes)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmptmdf4tet/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


[{'predictions': array([-0.9762077], dtype=float32)},
 {'predictions': array([-0.9010448], dtype=float32)},
 {'predictions': array([-0.82588184], dtype=float32)}]

In [79]:
for p in regressor.predict(funcao_previsao):
#     print(p['predictions'])
    print(scaler_y.inverse_transform(p['predictions']))

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmptmdf4tet/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
[181704.05]
[209297.73]
[236891.48]
