# Previsão do Preço de Casas com Regressão Linear Múltipla

Dataset: [House Sales in King County, USA](https://www.kaggle.com/harlfoxem/housesalesprediction)

In [1]:
import pandas as pd
base = pd.read_csv('data/house-prices.csv')
base.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view     ...      grade  sqft_above  \
0      5650     1.0           0     0     ...          7        1180   
1      7242     2.0           0     0     ...          7        2170   
2     10000     1.0           0     0     ...          6         770   
3      5000     1.0           0     0     ...          7        1050   
4      8080     1.0           0     0     ...          8        1680   

   sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
0              0      1955             0    98178  47.5112 -122.257   
1            400      1951          1991    98125  47.7210 -122.319   
2              0      1933             0    98028  47.7379 -122.233   
3            910      1965             0    98136  47.5208 -122.393   
4              0      1987             0    98074  47.6168 -122.045   

   sqft_living15  sqft_lot15  
0           1340        5650  
1           1690        7639  
2           2720        8062  
3           1360        5000  
4           1800        7503  

[5 rows x 21 columns]

In [3]:
base.columns

Index(['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long', 'sqft_living15', 'sqft_lot15'],
      dtype='object')

In [4]:
colunas_usadas = ['price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long']

In [5]:
colunas_usadas

['price',
 'bedrooms',
 'bathrooms',
 'sqft_living',
 'sqft_lot',
 'floors',
 'waterfront',
 'view',
 'condition',
 'grade',
 'sqft_above',
 'sqft_basement',
 'yr_built',
 'yr_renovated',
 'zipcode',
 'lat',
 'long']

In [6]:
base = pd.read_csv('data/house-prices.csv', usecols=colunas_usadas)

In [7]:
base.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  221900.0         3       1.00         1180      5650     1.0           0   
1  538000.0         3       2.25         2570      7242     2.0           0   
2  180000.0         2       1.00          770     10000     1.0           0   
3  604000.0         4       3.00         1960      5000     1.0           0   
4  510000.0         3       2.00         1680      8080     1.0           0   

   view  condition  grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0     0          3      7        1180              0      1955             0   
1     0          3      7        2170            400      1951          1991   
2     0          3      6         770              0      1933             0   
3     0          5      7        1050            910      1965             0   
4     0          3      8        1680              0      1987             0   

   zipcode      lat     long  
0    98178  47.5112 -122.257  
1    98125  47.7210 -122.319  
2    98028  47.7379 -122.233  
3    98136  47.5208 -122.393  
4    98074  47.6168 -122.045

In [9]:
from sklearn.preprocessing import MinMaxScaler
scaler_x = MinMaxScaler()

In [10]:
base[['bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long']] = scaler_x.fit_transform(base[['bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long']])

/home/felipe/.local/share/virtualenvs/tensorflow-machine-learning-deep-learning--rkUGFC5q/lib/python3.6/site-packages/sklearn/preprocessing/data.py:323: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)


In [11]:
base.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  221900.0  0.090909    0.12500     0.067170  0.003108     0.0         0.0   
1  538000.0  0.090909    0.28125     0.172075  0.004072     0.4         0.0   
2  180000.0  0.060606    0.12500     0.036226  0.005743     0.0         0.0   
3  604000.0  0.121212    0.37500     0.126038  0.002714     0.0         0.0   
4  510000.0  0.090909    0.25000     0.104906  0.004579     0.0         0.0   

   view  condition     grade  sqft_above  sqft_basement  yr_built  \
0   0.0        0.5  0.500000    0.097588       0.000000  0.478261   
1   0.0        0.5  0.500000    0.206140       0.082988  0.443478   
2   0.0        0.5  0.416667    0.052632       0.000000  0.286957   
3   0.0        1.0  0.500000    0.083333       0.188797  0.565217   
4   0.0        0.5  0.583333    0.152412       0.000000  0.756522   

   yr_renovated   zipcode       lat      long  
0      0.000000  0.893939  0.571498  0.217608  
1      0.988089  0.626263  0.908959  0.166113  
2      0.000000  0.136364  0.936143  0.237542  
3      0.000000  0.681818  0.586939  0.104651  
4      0.000000  0.368687  0.741354  0.393688

In [12]:
scaler_y = MinMaxScaler()

In [13]:
base[['price']] = scaler_y.fit_transform(base[['price']])

In [14]:
base.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  0.019266  0.090909    0.12500     0.067170  0.003108     0.0         0.0   
1  0.060721  0.090909    0.28125     0.172075  0.004072     0.4         0.0   
2  0.013770  0.060606    0.12500     0.036226  0.005743     0.0         0.0   
3  0.069377  0.121212    0.37500     0.126038  0.002714     0.0         0.0   
4  0.057049  0.090909    0.25000     0.104906  0.004579     0.0         0.0   

   view  condition     grade  sqft_above  sqft_basement  yr_built  \
0   0.0        0.5  0.500000    0.097588       0.000000  0.478261   
1   0.0        0.5  0.500000    0.206140       0.082988  0.443478   
2   0.0        0.5  0.416667    0.052632       0.000000  0.286957   
3   0.0        1.0  0.500000    0.083333       0.188797  0.565217   
4   0.0        0.5  0.583333    0.152412       0.000000  0.756522   

   yr_renovated   zipcode       lat      long  
0      0.000000  0.893939  0.571498  0.217608  
1      0.988089  0.626263  0.908959  0.166113  
2      0.000000  0.136364  0.936143  0.237542  
3      0.000000  0.681818  0.586939  0.104651  
4      0.000000  0.368687  0.741354  0.393688

In [15]:
X = base.drop('price', axis=1)

In [16]:
y = base.price

In [17]:
X.head()

bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view  \
0  0.090909    0.12500     0.067170  0.003108     0.0         0.0   0.0   
1  0.090909    0.28125     0.172075  0.004072     0.4         0.0   0.0   
2  0.060606    0.12500     0.036226  0.005743     0.0         0.0   0.0   
3  0.121212    0.37500     0.126038  0.002714     0.0         0.0   0.0   
4  0.090909    0.25000     0.104906  0.004579     0.0         0.0   0.0   

   condition     grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0        0.5  0.500000    0.097588       0.000000  0.478261      0.000000   
1        0.5  0.500000    0.206140       0.082988  0.443478      0.988089   
2        0.5  0.416667    0.052632       0.000000  0.286957      0.000000   
3        1.0  0.500000    0.083333       0.188797  0.565217      0.000000   
4        0.5  0.583333    0.152412       0.000000  0.756522      0.000000   

    zipcode       lat      long  
0  0.893939  0.571498  0.217608  
1  0.626263  0.908959  0.166113  
2  0.136364  0.936143  0.237542  
3  0.681818  0.586939  0.104651  
4  0.368687  0.741354  0.393688

In [18]:
y.head()

0    0.019266
1    0.060721
2    0.013770
3    0.069377
4    0.057049
Name: price, dtype: float64

In [19]:
type(X)

pandas.core.frame.DataFrame

In [20]:
type(y)

pandas.core.series.Series

In [21]:
previsores_colunas = colunas_usadas[1:]
previsores_colunas

['bedrooms',
 'bathrooms',
 'sqft_living',
 'sqft_lot',
 'floors',
 'waterfront',
 'view',
 'condition',
 'grade',
 'sqft_above',
 'sqft_basement',
 'yr_built',
 'yr_renovated',
 'zipcode',
 'lat',
 'long']

In [22]:
import tensorflow as tf

In [23]:
colunas = [tf.feature_column.numeric_column(key=c) for c in previsores_colunas]

In [24]:
colunas

[_NumericColumn(key='bedrooms', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='bathrooms', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='sqft_living', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='sqft_lot', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='floors', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='waterfront', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='view', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='condition', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='grade', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='sqft_above', shape=(1,), default_value=None, dtype=tf.

In [25]:
from sklearn.model_selection import train_test_split
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X, y, test_size=0.3)

In [26]:
X_treinamento.shape

(15129, 16)

In [27]:
y_treinamento.shape

(15129,)

In [28]:
funcao_treinamento = tf.estimator.inputs.pandas_input_fn(x=X_treinamento, y=y_treinamento, batch_size=32, num_epochs=None, shuffle=True)

In [29]:
funcao_teste = tf.estimator.inputs.pandas_input_fn(x=X_teste, y=y_teste, batch_size=32, num_epochs=10000, shuffle=False)

In [30]:
regressor = tf.estimator.LinearRegressor(feature_columns=colunas)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/tmp/tmpr86zjl0i', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f9ed2a469b0>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [31]:
regressor.train(input_fn=funcao_treinamento, steps=10000)

Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Saving checkpoints for 0 into /tmp/tmpr86zjl0i/model.ckpt.
INFO:tensorflow:loss = 0.1820513, step = 1
INFO:tensorflow:global_step/sec: 160.306
INFO:tensorflow:loss = 0.02097563, step = 101 (0.626 sec)
INFO:tensorflow:global_step/sec: 172.967
INFO:tensorflow:loss = 0.014820896, step = 201 (0.578 sec)
INFO:tensorflow:global_step/sec: 160.821
INFO:tensorflow:loss = 0.037777033, step = 301 (0.622 sec)
INFO:tensorflow:global_step/sec: 163.18
INFO:tensorflow:loss = 0.07635094, step = 401 (0.623 sec)

INFO:tensorflow:global_step/sec: 159.351
INFO:tensorflow:loss = 0.0142035335, step = 6701 (0.626 sec)
INFO:tensorflow:global_step/sec: 172.43
INFO:tensorflow:loss = 0.026781647, step = 6801 (0.580 sec)
INFO:tensorflow:global_step/sec: 163.751
INFO:tensorflow:loss = 0.018326003, step = 6901 (0.611 sec)
INFO:tensorflow:global_step/sec: 178.384
INFO:tensorflow:loss = 0.020470686, step = 7001 (0.561 sec)
INFO:tensorflow:global_step/sec: 183.072
INFO:tensorflow:loss = 0.027325861, step = 7101 (0.546 sec)
INFO:tensorflow:global_step/sec: 178.074
INFO:tensorflow:loss = 0.014802231, step = 7201 (0.564 sec)
INFO:tensorflow:global_step/sec: 167.524
INFO:tensorflow:loss = 0.05158639, step = 7301 (0.596 sec)
INFO:tensorflow:global_step/sec: 167.86
INFO:tensorflow:loss = 0.007084011, step = 7401 (0.593 sec)
INFO:tensorflow:global_step/sec: 182.755
INFO:tensorflow:loss = 0.021328807, step = 7501 (0.550 sec)
INFO:tensorflow:global_step/sec: 158.354
INFO:tensorflow:loss = 0.019622503, step = 7601 (0.6

In [32]:
metricas_treinamento = regressor.evaluate(input_fn=funcao_treinamento, steps=10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2019-01-14-10:39:40
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpr86zjl0i/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Evaluation [5000/10000]
INFO:tensorflow:Evaluation [6000/10000]
INFO:tensorflow:Evaluation [7000/10000]
INFO:tensorflow:Evaluation [8000/10000]
INFO:tensorflow:Evaluation [9000/10000]
INFO:tensorflow:Evaluation [10000/10000]
INFO:tensorflow:Finished evaluation at 2019-01-14-10:40:29
INFO:tensorflow:Saving dict for global step 10000: average_loss = 0.00068429904, global_step = 10000, label/mean = 0.060898546, loss = 0.02189757, prediction/mean = 0.06085592
INFO:tensorflow:Saving 'checkpoint_p

In [33]:
metricas_teste = regressor.evaluate(input_fn=funcao_teste, steps=10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2019-01-14-10:40:43
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpr86zjl0i/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Evaluation [5000/10000]
INFO:tensorflow:Evaluation [6000/10000]
INFO:tensorflow:Evaluation [7000/10000]
INFO:tensorflow:Evaluation [8000/10000]
INFO:tensorflow:Evaluation [9000/10000]
INFO:tensorflow:Evaluation [10000/10000]
INFO:tensorflow:Finished evaluation at 2019-01-14-10:41:32
INFO:tensorflow:Saving dict for global step 10000: average_loss = 0.00073752954, global_step = 10000, label/mean = 0.061223615, loss = 0.023600945, prediction/mean = 0.06180822
INFO:tensorflow:Saving 'checkpoint_

In [34]:
metricas_treinamento

{'average_loss': 0.00068429904,
 'label/mean': 0.060898546,
 'loss': 0.02189757,
 'prediction/mean': 0.06085592,
 'global_step': 10000}

In [35]:
metricas_teste

{'average_loss': 0.00073752954,
 'label/mean': 0.061223615,
 'loss': 0.023600945,
 'prediction/mean': 0.06180822,
 'global_step': 10000}

In [36]:
funcao_previsao = tf.estimator.inputs.pandas_input_fn(x=X_teste, shuffle=False)

In [37]:
previsoes = regressor.predict(input_fn=funcao_previsao)

In [38]:
list(previsoes)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpr86zjl0i/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


[{'predictions': array([0.13937807], dtype=float32)},
 {'predictions': array([0.01662873], dtype=float32)},
 {'predictions': array([0.0935463], dtype=float32)},
 {'predictions': array([0.07335114], dtype=float32)},
 {'predictions': array([0.04837112], dtype=float32)},
 {'predictions': array([0.19255702], dtype=float32)},
 {'predictions': array([0.02520116], dtype=float32)},
 {'predictions': array([0.01162786], dtype=float32)},
 {'predictions': array([0.00579811], dtype=float32)},
 {'predictions': array([0.13618125], dtype=float32)},
 {'predictions': array([0.04022107], dtype=float32)},
 {'predictions': array([0.05925596], dtype=float32)},
 {'predictions': array([0.06303881], dtype=float32)},
 {'predictions': array([0.05952321], dtype=float32)},
 {'predictions': array([0.08938737], dtype=float32)},
 {'predictions': array([0.05741327], dtype=float32)},
 {'predictions': array([0.05664705], dtype=float32)},
 {'predictions': array([0.0428206], dtype=float32)},
 {'predictions': array([0.0509

In [39]:
valores_previsoes = [p['predictions'] for p in regressor.predict(input_fn=funcao_previsao)]

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpr86zjl0i/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


In [40]:
valores_previsoes

[array([0.13937807], dtype=float32),
 array([0.01662873], dtype=float32),
 array([0.0935463], dtype=float32),
 array([0.07335114], dtype=float32),
 array([0.04837112], dtype=float32),
 array([0.19255702], dtype=float32),
 array([0.02520116], dtype=float32),
 array([0.01162786], dtype=float32),
 array([0.00579811], dtype=float32),
 array([0.13618125], dtype=float32),
 array([0.04022107], dtype=float32),
 array([0.05925596], dtype=float32),
 array([0.06303881], dtype=float32),
 array([0.05952321], dtype=float32),
 array([0.08938737], dtype=float32),
 array([0.05741327], dtype=float32),
 array([0.05664705], dtype=float32),
 array([0.0428206], dtype=float32),
 array([0.05094725], dtype=float32),
 array([0.04706168], dtype=float32),
 array([0.06265621], dtype=float32),
 array([0.04256562], dtype=float32),
 array([0.06500271], dtype=float32),
 array([0.05668853], dtype=float32),
 array([0.02997729], dtype=float32),
 array([0.09194596], dtype=float32),
 array([0.00637314], dtype=float32),
 ar

In [42]:
import numpy as np
valores_previsoes = np.asarray(valores_previsoes).reshape(-1, 1)

In [43]:
valores_previsoes

array([[0.13937807],
       [0.01662873],
       [0.0935463 ],
       ...,
       [0.0244507 ],
       [0.00641336],
       [0.19702713]], dtype=float32)

In [44]:
valores_previsoes = scaler_y.inverse_transform(valores_previsoes)

In [45]:
valores_previsoes

array([[1137757.8 ],
       [ 201794.03],
       [ 788290.5 ],
       ...,
       [ 261436.58],
       [ 123901.88],
       [1577331.9 ]], dtype=float32)

In [46]:
y_teste

21141    0.236721
17194    0.014721
16464    0.092452
5309     0.060328
11816    0.040000
7506     0.318033
19370    0.016380
12007    0.022951
18637    0.019331
12319    0.094443
2005     0.026479
2277     0.055738
4980     0.102951
19906    0.071738
20745    0.052852
10145    0.054885
18134    0.033443
9030     0.044590
17846    0.081967
7190     0.040066
14536    0.044590
278      0.049836
18817    0.049443
17372    0.055725
4898     0.022295
8333     0.111475
7376     0.028852
5185     0.022098
15152    0.272459
14685    0.182295
           ...   
9145     0.054098
7160     0.050492
10511    0.150820
14529    0.042623
18131    0.052459
18029    0.055475
17021    0.012885
16909    0.073443
2794     0.159213
8897     0.041639
17744    0.073443
2422     0.063869
15688    0.106754
2770     0.069377
12959    0.022369
11128    0.050492
3313     0.046295
17301    0.052459
11612    0.060984
3106     0.049115
6054     0.009836
8727     0.075410
8266     0.041180
15892    0.195410
13902    0

In [49]:
y_teste.shape

(6484,)

In [50]:
y_teste_as_matrix = y_teste.values.reshape(-1, 1)

In [52]:
y_teste_as_matrix.shape

(6484, 1)

In [53]:
y_teste_as_matrix = scaler_y.inverse_transform(y_teste_as_matrix)

In [54]:
y_teste_as_matrix

array([[1880000.],
       [ 187250.],
       [ 779950.],
       ...,
       [ 340000.],
       [ 225000.],
       [ 770000.]])

In [55]:
from sklearn.metrics import mean_absolute_error

In [56]:
mae = mean_absolute_error(y_teste_as_matrix, valores_previsoes)

In [57]:
mae

127305.28100261888