In [1]:
import tensorflow as tf

In [13]:
a = tf.constant([9, 8 ,7],name='a')

In [14]:
b = tf.constant([1,2,3], name='b')

In [15]:
soma = a + b

In [16]:
type(a)

tensorflow.python.framework.ops.Tensor

In [17]:
print(a)

Tensor("a_1:0", shape=(3,), dtype=int32)


In [18]:
with tf.Session() as sess:
    print(sess.run(soma))

[10 10 10]


In [19]:
a1 = tf.constant([[1,2,3], [4,5,6]], name='a1')
type(a1)
print(a1)

Tensor("a1:0", shape=(2, 3), dtype=int32)


In [20]:
a1.shape

TensorShape([Dimension(2), Dimension(3)])

In [25]:
b1 = tf.constant([[1, 2, 3], [4, 5, 6]], name='b1')

In [26]:
soma1 = tf.add(a1, b1, name='soma1')

In [31]:
with tf.Session() as sess:
    print(sess.run(a1), end='\n\n')
    print(sess.run(b1), end='\n\n')
    print(sess.run(soma1))


[[1 2 3]
 [4 5 6]]

[[1 2 3]
 [4 5 6]]

[[ 2  4  6]
 [ 8 10 12]]


In [32]:
a2 = tf.constant([[1,2,3], [4,5,6]])
b2 = tf.constant([[1], [2]])

In [34]:
with tf.Session() as s:
    print(s.run(a2), end='\n\n')
    print(s.run(b2), end='\n\n')

[[1 2 3]
 [4 5 6]]

[[1]
 [2]]



In [35]:
soma2 = tf.add(a2, b2)

In [37]:
with tf.Session() as s:
    print(s.run(soma2))

[[2 3 4]
 [6 7 8]]
