In [1]:
import tensorflow as tf

In [2]:
a = tf.constant([[1,2,], [3,4]])

In [3]:
b = tf.constant([[-1,3,], [4,2]])

In [4]:
mult = tf.matmul(a, b)

In [5]:
with tf.Session() as s:
    print(s.run(a))
    print()
    print(s.run(b))
    print()
    print(s.run(mult))

[[1 2]
 [3 4]]

[[-1  3]
 [ 4  2]]

[[ 7  7]
 [13 17]]


In [6]:
mult2 = tf.matmul(b, a)

In [7]:
with tf.Session() as s:
    print(s.run(a))
    print()
    print(s.run(b))
    print()
    print(s.run(mult2))

[[1 2]
 [3 4]]

[[-1  3]
 [ 4  2]]

[[ 8 10]
 [10 16]]


In [8]:
a1 = tf.constant([[2,3], [0, 1], [-1, 4]])
b1 = tf.constant([[1,2,3], [-2, 0, 4]])

In [9]:
mult3 = tf.matmul(a1,b1)

In [10]:
with tf.Session() as s:
    print(s.run(a1))
    print()
    print(s.run(b1))
    print()
    print(s.run(mult3))

[[ 2  3]
 [ 0  1]
 [-1  4]]

[[ 1  2  3]
 [-2  0  4]]

[[-4  4 18]
 [-2  0  4]
 [-9 -2 13]]


Para enteder melhor: [Multiplicação de Matrizes - Só Matemática](https://www.somatematica.com.br/emedio/matrizes/matrizes4.php)