In [1]:
import tensorflow as tf

In [11]:
p = tf.placeholder('float', None)

In [12]:
type(p)

tensorflow.python.framework.ops.Tensor

In [13]:
op = p + 2

In [15]:
with tf.Session() as s:
    # s.run(op)
    resultado = s.run(op, feed_dict={p: [1, 2, 3]})
    print(resultado)

[3.]


In [16]:
resultado

array([3.], dtype=float32)

In [17]:
p2 = tf.placeholder('float', [None, 5])

In [22]:
op2 = p2 * 5

In [23]:
with tf.Session() as s:
    # s.run(op)
    dados = [[1,2,3,4,5], [6,7,8,8,10]]
    r2 = s.run(op2, feed_dict={p2:dados})
    print(r2)

[[ 5. 10. 15. 20. 25.]
 [30. 35. 40. 40. 50.]]
